const MODULES = { market: "市场环境", pool: "候选与基本面", vcp: "VCP结构", signals: "信号与计划", portfolio: "持仓与风控", valuation: "估值与研究" };
const LABELS = { industry_sw_l1: "申万一级", industry_sw_l2: "申万二级", gn: "概念题材", fg: "风格特征" };
const INDEX_LABELS = { shanghai_composite: "上证综指", csi300: "沪深300", csi500: "中证500", csi1000: "中证1000", chinext: "创业板指", star50: "科创50" };
let context, currentKind = "industry_sw_l2", rankWindow = "rank_20", selectedName, matrixSelectedName, activeModule = "market";
const $ = (id) => document.getElementById(id), pct = (v, d = 2) => v == null ? "—" : `${Number(v).toFixed(d)}%`, cls = (v) => v > 0 ? "positive" : v < 0 ? "negative" : "";
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c]));

function renderModuleNav() { $("module-nav").innerHTML = Object.entries(MODULES).map(([key, label]) => `<button class="${key === activeModule ? "active" : ""}" data-module="${key}">${label}</button>`).join(""); $("module-nav").querySelectorAll("button").forEach((b) => b.onclick = () => { activeModule = b.dataset.module; renderModuleNav(); renderModule(); }); }
function renderModule() { const market = $("market-content"), placeholder = $("module-placeholder"), date = $("date-control"); if (activeModule === "market") { market.classList.remove("hidden"); placeholder.classList.add("hidden"); date.classList.remove("hidden"); return; } market.classList.add("hidden"); date.classList.add("hidden"); placeholder.innerHTML = `<p class="section-label">${MODULES[activeModule]}</p><h2>模块尚未发布展示数据</h2><p>后续该模块将通过 <code>dashboard/data/</code> 发布独立数据包，由本面板只读展示。</p>`; placeholder.classList.remove("hidden"); }
function renderStateRules() { const e=context.market_state_explainer, rules=$("state-rules"); if(!e)return; const metrics=e.current.metrics.map((v)=>`<div><span>${esc(v.label)}</span><b>${esc(v.value)}</b></div>`).join(""); const matched=e.current.matched.map((v)=>`<li>${esc(v)}</li>`).join(""); const states=e.states.map((v)=>`<tr class="${v.active?"active-rule":""}"><td>${esc(v.name)}${v.active?" <span class='tag'>当前</span>":""}</td><td>${esc(v.rule)}</td><td>${esc(v.confirm)}</td><td>${esc(v.meaning)}</td></tr>`).join(""); const scores=e.score_rules.map((v)=>`<article><h4>${esc(v.name)}</h4><p>${esc(v.rule)}</p><span>${esc(v.direction)}</span></article>`).join(""); rules.innerHTML=`<div class="rules-current"><div><p class="section-label">当前判定</p><h3>${esc(e.current.label)}</h3><ul>${matched}</ul></div><div class="rule-metrics">${metrics}</div></div><div class="rules-all"><p class="section-label">完整状态规则</p><div class="table-scroll"><table><thead><tr><th>状态</th><th>触发规则</th><th>确认</th><th>含义</th></tr></thead><tbody>${states}</tbody></table></div></div><div class="score-rules"><p class="section-label">四项分数口径</p><div>${scores}</div></div>`; }
function renderState() { const s = context.market_state, a = context.breadth.all_a; $("market-state").textContent = s.label; $("state-duration").textContent = `已持续 ${s.duration_days} 个交易日`; $("risk-tags").innerHTML = s.risk_tags.map((v) => `<span class="tag">${esc(v)}</span>`).join(""); $("state-analysis").textContent = s.analysis; const transition = $("state-transition"); if (s.transition) { transition.textContent = s.transition; transition.classList.remove("hidden"); } else transition.classList.add("hidden"); $("data-status").textContent = `数据更新至 ${context.meta.run_date} · 全A覆盖 ${a.valid_count}/${a.universe_size} (${pct(a.coverage_ratio * 100)}) · 板块历史：${context.meta.sector_history_note}`; renderStateRules(); }
function trendSparkline(v) { const data=v.trend_series||[], state=v.above_ma20&&v.above_ma60?"up":v.above_ma60?"pullback":"down", label={up:"上行结构",pullback:"回调观察",down:"弱势结构"}[state]; if(data.length<2)return `<span class="trend-sparkline ${state}">${label}</span>`; const width=132,height=42,pad=3,values=data.flatMap((p)=>[p.close,p.ma20,p.ma60]),min=Math.min(...values),max=Math.max(...values),span=max-min||1,y=(x)=>((max-x)/span*(height-pad*2)+pad).toFixed(1),points=(key)=>data.map((p,i)=>`${(i/(data.length-1)*(width-pad*2)+pad).toFixed(1)},${y(p[key])}`).join(" "); return `<span class="trend-sparkline ${state}" title="红线：价格；蓝线：MA20；灰线：MA60"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="20日价格与均线趋势"><polyline class="spark-ma60" points="${points("ma60")}"/><polyline class="spark-ma20" points="${points("ma20")}"/><polyline class="spark-close" points="${points("close")}"/></svg><small><b>${label}</b><i class="close"></i>价 <i class="ma20"></i>20 <i class="ma60"></i>60</small></span>`; }
function shortTrend(v) { return v.ma20_slope_5>=0.2?`<span class="trend-arrow up">↗ 上行</span>`:v.ma20_slope_5<=-0.2?`<span class="trend-arrow down">↘ 下行</span>`:`<span class="trend-arrow flat">→ 走平</span>`; }
function averageVolatility(v) { const level=v.volatility_score>=75?"high":v.volatility_score>=40?"medium":"low", label={high:"高波动",medium:"中波动",low:"低波动"}[level]; return `<span class="volatility ${level}" title="过去14个交易日的平均真实波幅占当前价格的比例">${label} <small>${pct(v.atr14_pct)}</small></span>`; }
function drawdown(v) { const value=v.distance_high60_pct; if(value>=-0.005)return `<span class="drawdown high">60日新高</span>`; const level=value>=-5?"shallow":value>=-15?"medium":"deep", label={shallow:"浅回撤",medium:"中度回撤",deep:"深度回撤"}[level]; return `<span class="drawdown ${level}">${label} <small>${pct(value)}</small></span>`; }
function recentVolume(v) { const value=v.volume_ratio_5_20??v.volume_ratio_20, level=value>=1.15?"active":value>=0.9?"normal":"contract", label={active:"活跃",normal:"常态",contract:"收缩"}[level]; return `<span class="recent-volume ${level}" title="5日平均成交量 / 20日平均成交量">${label} <small>${Number(value).toFixed(2)}x</small></span>`; }
function renderIndexes() { const rows = Object.entries(context.indexes).map(([n,v]) => `<tr><td>${esc(INDEX_LABELS[n] || n)}</td><td class="return-col ${cls(v.return_1)}">${pct(v.return_1)}</td><td class="return-col ${cls(v.return_5)}">${pct(v.return_5)}</td><td class="return-col ${cls(v.return_20)}">${pct(v.return_20)}</td><td>${drawdown(v)}</td><td>${trendSparkline(v)}</td><td>${recentVolume(v)}</td><td>${shortTrend(v)}</td><td>${averageVolatility(v)}</td></tr>`).join(""); $("index-table").innerHTML = `<thead><tr><th>指数</th><th class="return-col">1日</th><th class="return-col">5日</th><th class="return-col">20日</th><th>阶段位置</th><th>20日趋势</th><th>近期量能</th><th>短期趋势</th><th>14日平均波动</th></tr></thead><tbody>${rows}</tbody>`; }
function historyFor(name) { return (context.sector_history[currentKind] || []).find((v) => v.block_name === name)?.points || []; }
function renderSectorTabs() { $("sector-tabs").innerHTML = Object.entries(LABELS).map(([k,v]) => `<button class="${k === currentKind ? "active" : ""}" data-kind="${k}">${v}</button>`).join(""); $("sector-tabs").querySelectorAll("button").forEach((b) => b.onclick = () => { currentKind=b.dataset.kind; selectedName=null; renderSectors(); }); }
function renderRankTabs() { const labels={rank_20:"20日",rank_5:"5日"}; $("rank-window-tabs").innerHTML=Object.entries(labels).map(([k,v])=>`<button class="${k===rankWindow?"active":""}" data-window="${k}">${v}</button>`).join(""); $("rank-window-tabs").querySelectorAll("button").forEach((b)=>b.onclick=()=>{rankWindow=b.dataset.window;renderRankTabs();renderMatrix();}); }
function sectorStateTag(state) { const classes={"持续主线":"mainline","新晋强化":"strengthening","高位分歧":"divergence","轮动脉冲":"pulse","观察中":"watch","弱势退潮":"fading","历史积累中":"building"}; return `<span class="sector-state ${classes[state]||"watch"}">${esc(state)}</span>`; }
function renderDetail(row) { const h=historyFor(row.block_name), hr=h.slice(-10).reverse().map((v)=>`<tr><td>${v.trade_date}</td><td>#${v.rank_20}</td><td>#${v.rank_5}</td><td class="${cls(v.relative_strength_20)}">${pct(v.relative_strength_20)}</td><td class="${cls(v.relative_strength_5)}">${pct(v.relative_strength_5)}</td></tr>`).join(""); const metric=(label,value,klass="")=>`<div><span>${label}</span><b class="${klass}">${value}</b></div>`; $("sector-detail").innerHTML=`<p class="section-label">板块详情</p><h3>${esc(row.block_name)}</h3>${sectorStateTag(row.sector_state)}<div class="detail-grid detail-primary">${metric("20日排名", `#${row.rank_20}`)}${metric("5日排名", `#${row.rank_5}`)}${metric("20日相对强度", pct(row.relative_strength_20), cls(row.relative_strength_20))}${metric("5日相对强度", pct(row.relative_strength_5), cls(row.relative_strength_5))}</div><p class="detail-heading">收益与参与度</p><div class="detail-grid">${metric("20日中位收益", pct(row.return_20), cls(row.return_20))}${metric("成员数", row.member_count)}${metric("上涨占比", pct(row.up_breadth))}${metric("量能活跃", `${row.volume_activity.toFixed(2)}x`)}</div><p class="detail-heading">趋势扩散</p><div class="detail-grid">${metric("站上 MA20", pct(row.above_ma20_ratio))}${metric("站上 MA60", pct(row.above_ma60_ratio))}${metric("60日新高", pct(row.new_high_ratio))}${metric("强势股密度", pct(row.strong_stock_density))}</div><p class="detail-meta">阶段数据 ${h.length}/20 日｜${row.history_basis==="point_in_time"?"每日快照（点时）":"当前成分快照回填（非严格点时）"}</p><p class="detail-heading">近期阶段轨迹 <span>最新 10 日</span></p><table class="detail-history"><thead><tr><th>日期</th><th>20日排名</th><th>5日排名</th><th>20日相对</th><th>5日相对</th></tr></thead><tbody>${hr||"<tr><td colspan='5' class='muted'>历史积累中</td></tr>"}</tbody></table>`; }
function renderMatrix() { const days=(context.sector_rank_matrix[currentKind]?.[rankWindow]||[]).slice(-20).reverse(), head=Array.from({length:20},(_,i)=>`<th>#${i+1}</th>`).join(""), body=days.map((d)=>{const m=new Map(d.ranks.map((v)=>[v.rank,v]));return `<tr><td>${d.trade_date}</td>${Array.from({length:20},(_,i)=>{const v=m.get(i+1);return v?`<td class="matrix-cell ${v.rank<=10?"rank-hot":"rank-mid"} ${v.block_name===matrixSelectedName?"matrix-selected":""}" data-matrix-name="${esc(v.block_name)}" title="点击高亮该板块的全部历史位置">${esc(v.block_name)}</td>`:"<td class='matrix-cell muted'>—</td>";}).join("")}</tr>`;}).join(""); $("history-matrix").innerHTML=`<thead><tr><th>日期</th>${head}</tr></thead><tbody>${body||"<tr><td class='muted'>历史积累中</td></tr>"}</tbody>`; $("history-matrix").querySelectorAll("[data-matrix-name]").forEach((cell)=>cell.onclick=()=>{matrixSelectedName=matrixSelectedName===cell.dataset.matrixName?null:cell.dataset.matrixName;renderMatrix();}); }
function renderSectors() { renderSectorTabs(); const rows=context.sector_rankings[currentKind]||[]; if(!rows.length)return; if(!selectedName||!rows.some((v)=>v.block_name===selectedName))selectedName=rows[0].block_name; const body=rows.map((v)=>`<tr class="${v.block_name===selectedName?"selected":""}" data-name="${esc(v.block_name)}"><td>${v.rank_20}</td><td>${esc(v.block_name)}</td><td>${sectorStateTag(v.sector_state)}</td><td class="${cls(v.relative_strength_20)}">${pct(v.relative_strength_20)}</td><td class="${cls(v.relative_strength_5)}">${pct(v.relative_strength_5)}</td></tr>`).join(""); $("sector-table").innerHTML=`<thead><tr><th>20日排名</th><th>板块</th><th>当前状态</th><th>20日相对强度</th><th>5日相对强度</th></tr></thead><tbody>${body}</tbody>`; $("sector-table").querySelectorAll("tbody tr").forEach((tr)=>tr.onclick=()=>{selectedName=tr.dataset.name;renderSectors();}); renderDetail(rows.find((v)=>v.block_name===selectedName));renderRankTabs();renderMatrix(); }
function loadContext(date) { const contexts=window.QUANT_DASHBOARD_MARKET_CONTEXTS||{}; if(contexts[date])return Promise.resolve(contexts[date]); return new Promise((resolve,reject)=>{const script=document.createElement("script");script.src=`data/market_context_${date}.js`;script.onload=()=>resolve((window.QUANT_DASHBOARD_MARKET_CONTEXTS||{})[date]);script.onerror=()=>reject(new Error(`无法加载 ${date} 的市场数据`));document.head.appendChild(script);}); }
async function load(date){try{context=await loadContext(date);if(!context)throw new Error(`缺少 ${date} 的市场数据`);$("load-error").classList.add("hidden");renderState();renderIndexes();renderSectors();}catch(error){const n=$("load-error");n.textContent=error.message;n.classList.remove("hidden");}}
function main(){const data=window.QUANT_DASHBOARD_INDEX?.market;if(!data?.latest){const n=$("load-error");n.textContent="尚未生成市场展示数据，请先运行市场模块。";n.classList.remove("hidden");return;}const s=$("date-select");s.innerHTML=data.available.slice().sort().reverse().map((v)=>`<option value="${v}">${v}</option>`).join("");s.value=data.latest;s.onchange=()=>load(s.value);$("state-help-toggle").onclick=()=>{const rules=$("state-rules"), open=rules.classList.toggle("hidden"); $("state-help-toggle").setAttribute("aria-expanded", String(!open));};renderModuleNav();renderModule();load(s.value);}main();
