const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const num=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toFixed(d):"—",money=v=>Number.isFinite(Number(v))?`${num(v,2)} 元`:"—",pct=v=>Number.isFinite(Number(v))?`${num(v,1)}%`:"—";
const text=(item,keys)=>keys.map(k=>item?.[k]).find(v=>v!==undefined&&v!==null&&v!=="")??"—";
const sources=item=>(item?.source_ids||[]).length?`<span class="source-ids">证据：${esc(item.source_ids.join(" · "))}</span>`:"";
const query=new URLSearchParams(location.search),code=query.get("code"),catalog=window.QUANT_DASHBOARD_VALUATION_LATEST;
function error(message){$("report-error").textContent=message;$("report-error").classList.remove("hidden")}
function scenarios(obj){return `<div class="scenario-row"><span>悲观<b>${num(obj?.pessimistic)}</b></span><span>基准<b>${num(obj?.base)}</b></span><span>乐观<b>${num(obj?.optimistic)}</b></span></div>`}
function dateLabel(stamp){return stamp?.length===6?`20${stamp.slice(0,2)}-${stamp.slice(2,4)}-${stamp.slice(4,6)}`:"—"}
function median(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?(a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2):null}
function render(row){
 const v=row.valuation||{},thesis=row.investment_thesis||{},stats=row.research_stats||{},pe=row.pe_2026e||{},matrix=row.matrix_2026e||{},reverse=row.status?.reverse_check||{};
 document.title=`${row.name}（${row.code}）· 深度估值报告`;$("company-name").textContent=row.name;$("company-code").textContent=row.code;$("report-meta").textContent=`研究日期 ${dateLabel(row.analysis_date)}`;$("market-trade").textContent=thesis.market_trade||"—";$("company-stage").textContent=`公司阶段：${thesis.company_stage||"—"}`;$("core-judgement").textContent=thesis.core_judgement||"—";
 $("research-stats").innerHTML=[[stats.evidence_count,"份证据"],[stats.consensus_count,"家机构"],[stats.divergence_count,"个分歧"],[stats.verification_count,"个验证点"]].map(([n,l])=>`<div><b>${num(n,0)}</b><span>${l}</span></div>`).join("");
 $("reverse-check").textContent=reverse.triggered?`反向检查已触发 · ${reverse.discount_rate_desc||""}`:"反向检查未触发";
 const current=Number(v.current_price),cards=[["当前价格",v.current_price,v.price_date?`收盘价 · ${v.price_date} · ${v.price_source||"行情数据"}`:"行情日期缺失","current"],["悲观估值",v.pessimistic,current?`${pct((v.pessimistic/current-1)*100)} 空间`:"—",""] ,["基准估值",v.base,pct(v.base_upside_pct),"base"],["乐观估值",v.optimistic,current?`${pct((v.optimistic/current-1)*100)} 空间`:"—",""]];
 $("valuation-cards").innerHTML=cards.map(([l,x,s,c])=>`<article class="valuation-card ${c}"><span>${l}</span><b>${money(x)}</b><small class="${Number(String(s).replace('%',''))>=0?'positive':'negative'}">${s}</small></article>`).join("");
 const points=[["悲观",v.pessimistic],["基准",v.base],["乐观",v.optimistic],["当前",v.current_price]],values=points.map(x=>Number(x[1])).filter(Number.isFinite),min=Math.min(...values),max=Math.max(...values);$("valuation-track").innerHTML=`<div class="track-line">${points.map(([l,x])=>`<span class="track-dot ${l==='当前'?'current':''}" style="left:${max===min?50:((Number(x)-min)/(max-min)*100)}%"><i>${l} ${num(x)}</i></span>`).join("")}</div>`;
 const consensus=row.consensus||[],np26=consensus.map(x=>Number(text(x,["np_2026e","net_profit_2026e"]))).filter(Number.isFinite),np27=consensus.map(x=>Number(text(x,["np_2027e","net_profit_2027e"]))).filter(Number.isFinite);
 $("consensus-summary").innerHTML=[["机构数量",consensus.length],["2026E 中位利润",median(np26)==null?"—":`${num(median(np26))} 亿`],["2026E 预测区间",np26.length?`${num(Math.min(...np26))}–${num(Math.max(...np26))} 亿`:"—"],["2027E 中位利润",median(np27)==null?"—":`${num(median(np27))} 亿`]].map(([l,x])=>`<div><span>${l}</span><b>${x}</b></div>`).join("");
 $("consensus-table").innerHTML=`<thead><tr><th>机构</th><th>报告日期</th><th>2026E 净利</th><th>2027E 净利</th><th>2026E 收入</th><th>2026E PE</th><th>目标价</th></tr></thead><tbody>${consensus.map(x=>`<tr><td><b>${esc(x.institution)}</b></td><td>${esc(x.report_date||"—")}</td><td>${num(text(x,["np_2026e","net_profit_2026e"]))}</td><td>${num(text(x,["np_2027e","net_profit_2027e"]))}</td><td>${num(x.revenue_2026e)}</td><td>${num(x.pe_2026e,1)}</td><td>${num(x.target_price)}</td></tr>`).join("")||"<tr><td colspan='7'>暂无结构化一致预期</td></tr>"}</tbody>`;
 const range=pe.step1_comparable_range||{};$("pe-panel").innerHTML=[["可比区间",`${num(range.lower,1)}–${num(range.upper,1)}x`],["最终 PE",`${num(pe.final_pe,1)}x`],["三情景 PE",`${num(pe.pessimistic_pe,1)} / ${num(pe.final_pe,1)} / ${num(pe.optimistic_pe,1)}x`],["增长质量",pe.growth_quality||"—"],["市场地位",pe.market_position||"—"],["定性调整",pct((pe.step3_qual_total||0)*100)]].map(([l,x])=>`<div><span>${l}</span><b>${esc(x)}</b></div>`).join("")+`<div class="pe-detail">${esc(pe.details||"")}</div>`;
 $("comparable-table").innerHTML=`<thead><tr><th>估值锚 / 可比</th><th>PE</th><th>增速</th><th>毛利率</th></tr></thead><tbody>${(row.comparables||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${num(x.pe,1)}x</td><td>${pct(x.growth_rate)}</td><td>${pct(x.gross_margin)}</td></tr>`).join("")||"<tr><td colspan='4'>暂无结构化可比数据</td></tr>"}</tbody>`;
 $("matrix-table").innerHTML=`<thead><tr><th>利润支柱（2026E，亿元）</th><th>Layer 1 悲观</th><th>基准</th><th>乐观</th><th>Layer 2 悲观</th><th>基准</th><th>乐观</th><th>总计基准</th></tr></thead><tbody>${(matrix.matrix_rows||[]).map(x=>`<tr><td>${esc(x.pillar_name)}</td><td>${num(x.layer1?.pessimistic)}</td><td>${num(x.layer1?.base)}</td><td>${num(x.layer1?.optimistic)}</td><td>${num(x.layer2?.pessimistic)}</td><td>${num(x.layer2?.base)}</td><td>${num(x.layer2?.optimistic)}</td><td><b>${num(x.pillar_total?.base)}</b></td></tr>`).join("")}<tr><td><b>合计市值</b></td><td colspan="6"></td><td><b>${num(matrix.total?.base)} 亿</b></td></tr></tbody>`;
 $("layer-cards").innerHTML=[["Layer 1","共识基线",matrix.layers_summary?.layer1],["Layer 2","分歧调整",matrix.layers_summary?.layer2],["Layer 3","叙事期权",matrix.layers_summary?.layer3]].map(([l,s,x])=>`<article class="layer-card"><h3>${l} · ${s}</h3>${scenarios(x)}<p>${esc(x?.pricing_status||"")}</p></article>`).join("");
 $("pillar-cards").innerHTML=(row.business_pillars||[]).map((x,i)=>{const bridge=x.profit_bridge||{},mapping=x.calculation_mapping||{},calc=(row.calc_pillars||[]).find(p=>p.name===x.name)||{};const bridgeList=items=>(items||[]).map(y=>`<li>${esc(y.item)}${Number(y.profit_impact)?` <b>${Number(y.profit_impact)>0?'+':''}${num(y.profit_impact)} 亿</b>`:''}${sources(y)}</li>`).join("")||"<li>未量化</li>";return `<article class="pillar-card"><div class="card-top"><h3>${String(i+1).padStart(2,'0')} · ${esc(x.name)}</h3><div class="badges"><span class="badge">${esc(x.classification||"—")}</span><span class="badge">路线 ${esc(mapping.route||calc.route||"排除")}</span><span class="badge">${esc(mapping.target||"—")}</span></div></div><p class="pillar-summary"><b>业务实质：</b>${esc(x.business_essence||"—")}<br><b>拆分理由：</b>${esc(x.split_rationale||"—")}</p><div class="pillar-grid"><div><h4>2026E 利润桥 · 2025A 基数 ${num(bridge.base_2025a)} 亿</h4><ul class="bridge-list">${bridgeList(bridge.items_2026e)}</ul></div><div><h4>2027E 延续项目</h4><ul class="bridge-list">${bridgeList(bridge.items_2027e)}</ul>${calc.layer2?.description?`<p class="pillar-summary"><b>Layer 2：</b>${esc(calc.layer2.description)}</p>`:""}</div></div>${sources(x)}</article>`}).join("");
 $("divergence-cards").innerHTML=(row.market_divergences||[]).map(x=>`<article class="divergence-card"><h3>${esc(x.name)}<span class="source-ids">${esc(x.pillar||"")} · ${x.pricing_status==='priced_in'?'已定价':'未充分定价'}</span></h3><div class="case bull"><b>乐观情形</b>${esc(x.bull_case)}</div><div class="case bear"><b>悲观情形</b>${esc(x.bear_case)}</div><div class="case ours"><b>我们的判断</b>${esc(x.our_judgement)}<span class="source-ids">根因：${esc(x.root_cause||"—")}</span></div></article>`).join("")||"<p>暂无结构化分歧。</p>";
 $("option-cards").innerHTML=(row.narrative_options||[]).map(x=>`<article class="option-card ${x.included_in_valuation?'included':''}"><span class="badge">${x.included_in_valuation?'已计入估值':'仅观察，不计入'}</span><h3>${esc(x.name)}</h3><p>${esc(x.business_essence)}<br><b>映射：</b>${esc(x.calculation_mapping?.target||"exclude")} · ${esc(x.calculation_mapping?.note||"")}</p><div class="option-value"><div><span>潜在利润</span><b>${num(x.potential_profit)} 亿</b></div><div><span>估值倍数</span><b>${num(x.pe,1)}x</b></div><div><span>实现概率</span><b>${pct(Number(x.probability)*100)}</b></div></div>${sources(x)}</article>`).join("")||"<p>暂无叙事期权。</p>";
 $("verification-list").innerHTML=(row.verification_nodes||[]).map(x=>`<article class="verification-item"><div class="verification-time">${esc(x.timeframe||"待定")}</div><div class="verification-line"></div><div class="verification-body"><h3>${esc(x.event)}</h3><span>${esc(x.node_id||"")} · ${esc(x.pillar||"")}</span><div class="meaning-grid"><p><b>验证成功：</b>${esc(x.success_meaning||"—")}</p><p><b>验证失败：</b>${esc(x.failure_meaning||"—")}</p></div>${sources(x)}</div></article>`).join("");
 $("facts-list").innerHTML=(row.facts||[]).map(x=>`<li>${esc(text(x,["statement","fact","description"]))}${sources(x)}</li>`).join("")||"<li>—</li>";$("assumptions-list").innerHTML=(row.assumptions||[]).map(x=>`<li><b>${esc(text(x,["name","assumption"]))}</b>${x.name?`：${esc(x.value)}`:""}${x.rationale?`<br>${esc(x.rationale)}`:""}${sources(x)}</li>`).join("")||"<li>—</li>";
 $("risks-list").innerHTML=(row.risks||[]).map(x=>`<li>${esc(text(x,["statement","description","risk"]))}${sources(x)}</li>`).join("")||"<li>—</li>";$("catalysts-list").innerHTML=(row.catalysts||[]).map(x=>`<li><b>${esc(text(x,["timeframe","time"]))}</b> · ${esc(x.event||"—")}${sources(x)}</li>`).join("")||"<li>—</li>";
 const evidence=row.evidence||[];$("evidence-summary").textContent=`${evidence.length} 条原始证据 · 点击查看来源与缓存定位`;$("evidence-table").innerHTML=`<thead><tr><th>ID</th><th>标题 / 类型</th><th>日期</th><th>来源</th><th>缓存定位</th></tr></thead><tbody>${evidence.map(x=>`<tr><td>${esc(x.source_id)}</td><td>${esc(x.title||x.source_type||"—")}</td><td>${esc(x.published_at||"—")}</td><td>${esc(x.source||x.provider||"—")}</td><td>${esc(x.cache_path||"—")}</td></tr>`).join("")}</tbody>`;$("run-id").textContent=`运行包 ${row.run_id}`;$("report-content").classList.remove("hidden")
}
if(!catalog)error("最新估值数据包尚未发布。");else if(!code)error("缺少股票代码。");else{const row=(catalog.valuations||[]).find(x=>x.code===code);row?render(row):error("没有找到该标的的已验证估值报告。")}
